### ISSUE TITLE
Selecting Midi File and Clicking on Open Does Nothing.

### ISSUE THREAD

**Issue by Bj007pro** [dudehacker/Automap-chan#1]
I have reopened the program up several times, selecting my Midi file, and clicking on the Open button but nothing happens not even an error message window. If I don't select a Midi file an information message window shows up telling me to select a Midi file, fine.

Am I doing something wrong, or is my copy of the program bugged and maybe need to redownload it?

Thanks.

Bj007pro

**Comment by dudehacker** [comment]
@Bj007pro I need more info to debug this issue. Since I can't reproduce it myself.
1. What is your OS and Java version?
2. What is the midi file you are trying to convert? It might be an issue with the file itself.
3. Please run the application with console and give me the stack trace.

**Comment by Bj007pro** [comment]
> @Bj007pro I need more info to debug this issue. Since I can't reproduce it myself.
> 
> 1. What is your OS and Java version?
> 2. What is the midi file you are trying to convert? It might be an issue with the file itself.
> 3. Please run the application with console and give me the stack trace.

1.) I only installed Java 64-bit just 10 days ago to play an open-source Tetris fan-game called [NullpoMino](https://github.com/nullpomino/nullpomino).
2.) No, it's not the file itself because it plays fine in VLC Media Player, Synthesia, and MidiTrail, also doesn't matter what Midi file I try to open.  - Also, most of my midi files are from Musescore.com.
3.) I'm not a developer so I don't know what you're saying here.

**Comment by dudehacker** [comment]
@Bj007pro Open Command Prompt (cmd), a black window.
use this command: java "filename". it will show the error log after

**Comment by Ticle** [comment]
Hello! Same problem here. I tried to open Midi files through Automap-chan, but 'Open' butten didn't work at all. Perfectly same as Bj007pro, no error messages.
I thought this it all my fault and followed the sentences: "put all files (except your midi) at same location as the jar file."
I tried execute jar file when other files(which below the "put all files" comment) are zipped and unzipped, still didn't work.

1. OS: My OS is Window 7 64bit. JAVA: Using latest version of Java. 
++ I tested my other computer, and its OS is Window 10, Latest version of Java.
2. I converted 'https://musescore.com/deemo_harlos/deerstalker' as Midi file. I'll try other Midi file.
3. I'm afraid I can't use console because didn't know about that. I tried java "filename" cmd... but it says cant load. Maybe I must have done something wrong. Could you say to me more details easier?

I hope I can help you and be friend with Automap-chan ^---^

**Comment by Bj007pro** [comment]
> @Bj007pro Open Command Prompt (cmd), a black window.
> use this command: java "filename". it will show the error log after

![image](https://user-images.githubusercontent.com/24400879/51486899-c4172900-1e06-11e9-9c51-33242da657d6.png)


Yeah, I tried several different ways but none of them worked, maybe a bit more detail would be nice, Dudehacker, please.

**Comment by dudehacker** [comment]
@Bj007pro sorry, the correct command is: java -jar "filename.jar"

**Comment by Bj007pro** [comment]
> @Bj007pro sorry, the correct command is: java -jar "filename.jar"

Ok, I think I got what you wanted, I hope this is corrected! :)

![image](https://user-images.githubusercontent.com/24400879/51490591-a484fe00-1e10-11e9-9813-d202290e42d8.png)

**Comment by Bj007pro** [comment]
> @Bj007pro sorry, the correct command is: java -jar "filename.jar"

Ok, I think I got what you wanted, I hope this is corrected! :)

![image](https://user-images.githubusercontent.com/24400879/51490661-d0a07f00-1e10-11e9-96cb-37b4f69c1e44.png)

**Comment by dudehacker** [comment]
@Bj007pro yes thats what i need to debug, thank you.
will work on it when i get off work in 6h

**Comment by dudehacker** [comment]
@Bj007pro @Ticle I have fixed the issue.

You can download the new release [here](https://github.com/dudehacker/Automap-chan/releases/latest)
